### PR TITLE
Update chrome.py & fix 'in <string>' requires string as left operand, not int error

### PR DESCRIPTION
**Pull request by kousha1999**
Just fixed `'in <string>' requires string as left operand, not int` 
Changed =>` passwd = ''.join(i for i in _passwd if i in string.printable)`
To => `passwd = ''.join(i for i in str(_passwd) if i in string.printable)`

### CODE REVIEW

**Comment by x899** [comment]
On which OS you are running this code? Windows?

**Comment by kousha1999** [comment]
> 
> 
> On which OS you are running this code? Windows?

Yes.

**Comment by x899** [comment]
In Linux and Mac's decrypt_func function, i am converting bytes to string by using decode('utf8').
However, I missed that in Windows. Thanks for pointing that out.

Instead of converting _passwd to string, please modify it in line no. 59 to `return data[1].decode('utf8')` like I did in other decrypt_func functions. And raise the PR again.

**Comment by kousha1999** [comment]
> 
> 
> In Linux and Mac's decrypt_func function, i am converting bytes to string by using decode('utf8').
> However, I missed that in Windows. Thanks for pointing that out.
> 
> Instead of converting _passwd to string, please modify it in line no. 59 to `return data[1].decode('utf8')` like I did in other decrypt_func functions. And raise the PR again.

Oh. That's right.
Okay. I'll PR now.
Thanks pal

**Comment by x899** [comment]
Enjoy your cookie now 🍪

**Comment by x899** [comment]
Fixes #2

**Pull request merged**
